/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoadsRouteImport } from './routes/loads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutineIndexRouteImport } from './routes/routine/index'
import { Route as EquipmentIndexRouteImport } from './routes/equipment/index'
import { Route as RoutineDayRouteImport } from './routes/routine/$day'
import { Route as ExerciseIdRouteImport } from './routes/exercise/$id'
import { Route as EquipmentIdRouteImport } from './routes/equipment/$id'

const LoadsRoute = LoadsRouteImport.update({
  id: '/loads',
  path: '/loads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineIndexRoute = RoutineIndexRouteImport.update({
  id: '/routine/',
  path: '/routine/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineDayRoute = RoutineDayRouteImport.update({
  id: '/routine/$day',
  path: '/routine/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseIdRoute = ExerciseIdRouteImport.update({
  id: '/exercise/$id',
  path: '/exercise/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIdRoute = EquipmentIdRouteImport.update({
  id: '/equipment/$id',
  path: '/equipment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loads': typeof LoadsRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/exercise/$id': typeof ExerciseIdRoute
  '/routine/$day': typeof RoutineDayRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/routine/': typeof RoutineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loads': typeof LoadsRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/exercise/$id': typeof ExerciseIdRoute
  '/routine/$day': typeof RoutineDayRoute
  '/equipment': typeof EquipmentIndexRoute
  '/routine': typeof RoutineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loads': typeof LoadsRoute
  '/equipment/$id': typeof EquipmentIdRoute
  '/exercise/$id': typeof ExerciseIdRoute
  '/routine/$day': typeof RoutineDayRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/routine/': typeof RoutineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/loads'
    | '/equipment/$id'
    | '/exercise/$id'
    | '/routine/$day'
    | '/equipment/'
    | '/routine/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/loads'
    | '/equipment/$id'
    | '/exercise/$id'
    | '/routine/$day'
    | '/equipment'
    | '/routine'
  id:
    | '__root__'
    | '/'
    | '/loads'
    | '/equipment/$id'
    | '/exercise/$id'
    | '/routine/$day'
    | '/equipment/'
    | '/routine/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoadsRoute: typeof LoadsRoute
  EquipmentIdRoute: typeof EquipmentIdRoute
  ExerciseIdRoute: typeof ExerciseIdRoute
  RoutineDayRoute: typeof RoutineDayRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
  RoutineIndexRoute: typeof RoutineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loads': {
      id: '/loads'
      path: '/loads'
      fullPath: '/loads'
      preLoaderRoute: typeof LoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine/': {
      id: '/routine/'
      path: '/routine'
      fullPath: '/routine/'
      preLoaderRoute: typeof RoutineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine/$day': {
      id: '/routine/$day'
      path: '/routine/$day'
      fullPath: '/routine/$day'
      preLoaderRoute: typeof RoutineDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise/$id': {
      id: '/exercise/$id'
      path: '/exercise/$id'
      fullPath: '/exercise/$id'
      preLoaderRoute: typeof ExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$id': {
      id: '/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/equipment/$id'
      preLoaderRoute: typeof EquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoadsRoute: LoadsRoute,
  EquipmentIdRoute: EquipmentIdRoute,
  ExerciseIdRoute: ExerciseIdRoute,
  RoutineDayRoute: RoutineDayRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
  RoutineIndexRoute: RoutineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
