/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs/index'
import { Route as TabsBrowseRouteImport } from './routes/_tabs/browse'
import { Route as TabsReportsRouteImport } from './routes/_tabs/reports'
import { Route as MIdRouteImport } from './routes/m.$id'

const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsBrowseRoute = TabsBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => TabsRoute,
} as any)
const TabsReportsRoute = TabsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TabsRoute,
} as any)
const MIdRoute = MIdRouteImport.update({
  id: '/m/$id',
  path: '/m/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/browse': typeof TabsBrowseRoute
  '/reports': typeof TabsReportsRoute
  '/m/$id': typeof MIdRoute
}
export interface FileRoutesByTo {
  '/browse': typeof TabsBrowseRoute
  '/reports': typeof TabsReportsRoute
  '/m/$id': typeof MIdRoute
  '/': typeof TabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/_tabs/browse': typeof TabsBrowseRoute
  '/_tabs/reports': typeof TabsReportsRoute
  '/m/$id': typeof MIdRoute
  '/_tabs/': typeof TabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/browse' | '/reports' | '/m/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/browse' | '/reports' | '/m/$id' | '/'
  id:
    | '__root__'
    | '/_tabs'
    | '/_tabs/browse'
    | '/_tabs/reports'
    | '/m/$id'
    | '/_tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
  MIdRoute: typeof MIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/browse': {
      id: '/_tabs/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof TabsBrowseRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/reports': {
      id: '/_tabs/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof TabsReportsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/m/$id': {
      id: '/m/$id'
      path: '/m/$id'
      fullPath: '/m/$id'
      preLoaderRoute: typeof MIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TabsRouteChildren {
  TabsBrowseRoute: typeof TabsBrowseRoute
  TabsReportsRoute: typeof TabsReportsRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsBrowseRoute: TabsBrowseRoute,
  TabsReportsRoute: TabsReportsRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
  MIdRoute: MIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
